# Generated by Django 2.2 on 2021-04-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloguser', '0002_dailyvisitnum_totalvisitnum_uservisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyvisitnum',
            name='day',
            field=models.DateField(default='2021-04-14'),
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='day',
            field=models.DateField(default='2021-04-14'),
        ),
    ]
