# Generated by Django 2.2 on 2021-04-27 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish_time']},
        ),
    ]
